### ISSUE TITLE
允许诊断工具在 .NET Framework 4 上面运行

### ISSUE THREAD

**Issue by lanyizi** [richcfno1/RA3Diagnosis#3]
诊断工具强制要求 .NET Framework 3.5

但是现在很多人的电脑上没有 .NET Framework 3.5，他们只有 .NET Framework 4+ （或者更高的版本），那他们就运行不了诊断工具了，除非他们把 3.5 也给装了。

我看了一下微软文档，似乎可以通过一个文件来「声明」程序可以在后续的 .NET Framework 版本上运行：
https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5

**Comment by richcfno1** [comment]
需要同时分发*.exe.config

**Comment by richcfno1** [comment]
#4
